Repository FRONTENDSCHOOL6/TMI-TodayMoIpji, pull requests merged in 2023-09, with the labels that each got.

#13 :recycle: Refactor: 해시라우터로 변경 및 파일 수정
  package.json
  public/Filter.svg
  public/Search.svg
  src/App.css
  src/App.jsx
  src/api/pocketbase.js
  src/components/Feed/Feed.jsx
  src/components/Feed/Feed.module.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/Writing.jsx
  src/routes.jsx
Labels: Refactor

#14 Feed, Post, Writing
  src/components/Feed/Feed.jsx
  src/components/Feed/Feed.module.css
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/components/Spinner.jsx
  src/hooks/useFeedItem.js
  src/hooks/useFetchData.js
  src/main.jsx
  src/pages/Post.jsx
  src/pages/Writing.jsx
  src/routes.jsx
  src/store/auth.js
  src/utils/getPbImageURL.js
Labels: Fix, Design

#29 Home -
  src/components/Feed/Feed.jsx
  src/components/Feed/Feed.module.css
  src/components/FeedItem.jsx/FeedItem.jsx
  src/components/FeedItem.jsx/FeedItem.module.css
  src/components/ProtectRoute.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/pages/Home.jsx
  src/routes.jsx
Labels: Feat, Fix, Refactor

#30 Post
  package.json
  pnpm-lock.yaml
  public/BackIcon.svg
  public/heart.svg
  src/App.jsx
  src/components/Feed/Feed.jsx
  src/components/FeedItem.jsx/FeedItem.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/FormInput/FormInput.jsx
  src/components/Heart.jsx
  src/components/MoveSlide/MoveSlide.jsx
  src/components/MoveSlide/MoveSlide.module.css
  src/components/SpeechBubble/SpeechBubble.jsx
  src/components/SpeechBubble/SpeechBubble.module.css
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
  src/routes.jsx
  src/styles/tailwind.css
  src/utils/formatDate.js
  src/utils/getSlideIndex.js
  src/utils/index.js
Labels: Feat, Design

#31 Writing-머지 및 버그 수정
  public/photoIcon.svg
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/pages/Writing.jsx
Labels: bug, Feat

#32 User, Profile Edit 머지
  src/assets/defalutProfilePic.png
  src/assets/userEmoji.svg
  src/components/DarkModeButton/DarkModeButton.jsx
  src/components/EditPageButton/EditPageButton.jsx
  src/components/FollowButton/FollowButton.jsx
  src/components/LoginButton/LoginButton.jsx
  src/components/ProfileUpload/ProfileUpload.jsx
  src/components/UserFeed/UserFeed.jsx
  src/components/UserNickname/UserNickname.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfilePicture/UserProfilePicture.jsx
  src/pages/GuestSetting.jsx
  src/pages/User.jsx
  src/pages/UserProfileEdit.jsx
  src/routes.jsx
  tailwind.config.js
Labels: Feat, Design

#36 Home 머지 후 수정
  pnpm-lock.yaml
  src/App.jsx
  src/components/Feed/Feed.jsx
  src/components/FeedItem.jsx/FeedItem.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/Heading/Heading.jsx
  src/components/MoveSlide/MoveSlide.jsx
  src/components/SearchBar/SearchBar.jsx
  src/layout/DarkModeContext.jsx
  src/layout/Nav.jsx
  src/layout/RootLayout.jsx
  src/pages/Home.jsx
  src/pages/Mypage.jsx
  src/pages/Post/Post.jsx
  src/routes.jsx
  src/store/useSearchStore.js
Labels: Fix

#38 Post - 라우팅 버그 수정 및 로그인한 사용자만 이용가능 컨텐츠
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/ProtectRoute.jsx
  src/hooks/useStorage.js
  src/layout/RootLayout.jsx
  src/main.jsx
  src/pages/Post.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
  src/routes.jsx
Labels: Feat, Fix

#39 Home
  src/App.jsx
  src/components/Feed/Feed.jsx
  src/components/FeedItem.jsx/FeedItem.jsx
  src/components/SearchBar/SearchBar.module.css
  src/routes.jsx
Labels: Fix, Design

#40 :lipstick: Design: 전체 레이아웃 수정
  src/components/Feed/Feed.module.css
  src/components/FileUpload/FileUpload.module.css
  src/layout/RootLayout.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
  src/pages/Writing.jsx
  src/styles/scrollbar.css
Labels: Design

#41 Home -배포작업 및 머지했습니다
  package.json
  pnpm-lock.yaml
  src/components/Feed/Feed.jsx
  src/components/FileUpload/FileUpload.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/Home.jsx
  src/pages/Post/Post.jsx
  src/pages/Writing.jsx
  vite.config.js
Labels: Fix, Deploy

#42 Writing - 버그 수정 및 로딩화면 추가 했습니
  public/TMI-Text.svg
  src/components/FileUpload/FileUpload.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/Heading/Heading.jsx
  src/components/Loading/Loading.jsx
  src/components/Loading/Loading.module.css
  src/components/LoadingSpinner.jsx
  src/components/Logo.jsx
  src/components/MoveSlide/MoveSlide.module.css
  src/pages/Post/Post.jsx
  src/pages/SignIn.jsx
Labels: Feat, Fix, Rename

#43 signUp page 기능구현입니다
  src/components/Button/Button.module.css
  src/layout/Nav.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/Welcome.jsx
  src/store/auth.js
  src/utils/validation.js
Labels: Feat, Fix, Design, Chore, Remove

#45 전체적인 레이아웃 수정했습니다
  public/degree.svg
  src/App.jsx
  src/App.module.css
  src/components/FileUpload/FileUpload.module.css
  src/components/Heading/Heading.jsx
  src/components/Heading/Heading.module.css
  src/components/Loading/Loading.module.css
  src/layout/FooterBar.jsx
  src/layout/RootLayout/RootLayout.jsx
  src/layout/RootLayout/RootLayout.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.css
  src/pages/Mypage.jsx
  src/pages/Mypage.module.css
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/Suggestion/Suggestion.jsx
  src/pages/Suggestion/Suggestion.module.css
  src/pages/UserProfileEdit.jsx
  src/pages/Welcome.jsx
  src/pages/Writing.jsx
  src/routes.jsx
Labels: Design

#46 loginpage branch 수정내용입니다
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/pages/Welcome.jsx
Labels: Feat, Refactor

#47 Suggest
  src/api/openweathermap.js
  src/components/FeedItem.jsx/FeedItem.jsx
  src/components/FileUpload/FileUpload.module.css
  src/components/GuestOnlyRoute.jsx
  src/components/Heading/Heading.jsx
  src/components/Heading/Heading.module.css
  src/layout/Nav.jsx
  src/pages/Mypage.jsx
  src/pages/Post/Post.jsx
  src/pages/Suggestion/Suggestion.jsx
  src/pages/Suggestion/Suggestion.module.css
  src/routes.jsx
Labels: Feat, Design, Refactor

#48 머지 부탁드립니다~!
  src/components/LoginButton/LoginButton.jsx
  src/components/UserProfilePicture/UserProfilePicture.jsx
  src/pages/GuestSetting.jsx
  src/pages/Mypage.jsx
  src/pages/UserProfileEdit.jsx
  src/routes.jsx
Labels: Feat, Refactor

#51 loginpage branch 수정사항입니다.
  src/pages/SignIn.jsx
  src/pages/SignIn.module.css
  src/pages/SignUp.jsx
  src/pages/SignUp.module.css
  src/pages/Welcome.jsx
  src/pages/Welcome.module.css
Labels: bug, Style, Design

#52 PR보냅니다
  src/pages/UserProfileEdit/UserProfileEdit.jsx
  src/pages/UserProfileEdit/UserProfileEdit.module.css
  src/routes.jsx
Labels: Refactor

#54 Common
  src/components/DarkModeButton/DarkModeButton.jsx
  src/pages/GuestSetting.jsx
  src/pages/Mypage/Mypage.jsx
  src/swiper/MypageStyleSlide.jsx
Labels: Fix

#56 :memo: Docs: 리드미 수정
  README.md
Labels: Docs

#57 Test merge
  src/components/Feed/Feed.jsx
  src/components/MyItem/MyItem.jsx
  src/layout/Nav/Nav.jsx
  src/pages/GuestSetting.jsx
  src/pages/Mypage.jsx
  src/pages/Mypage/Mypage.jsx
Labels: Fix, Design
